# -*- coding: utf-8 -*-
"""Copy of flask_rawdata_skull_stripping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OKnzdACyTNxGlAdGhZmp11yb3NeluVUG
"""
'''
!pip install medpy
!pip install deepbrain
!pip install -U scipy==1.2.0
!pip install tensorflow==1.15.2

cd ~
'''




from medpy.io import load
from deepbrain import Extractor
from PIL import Image, ImageDraw
import matplotlib.image as mpimg
import matplotlib.pyplot as plt
import scipy
import scipy.misc
import sys
import os
def stripping(path, spath):
    print("here is the path" + path)
    rawimg, image_header = load(path)
    t = rawimg
    # print(rawimg.shape)
    plt.imshow(t[:, :, 80], cmap=plt.get_cmap('gray'))
    for i in range(193):
        scipy.misc.imsave('static/uploads1/'+str(i) +
                          'ws'+'.jpg', rawimg[:, :, i])

    ext = Extractor()
    prob = ext.run(t)
    mask = (prob > 0.5)
    print(mask.shape)
    br = rawimg[:]
    br[~mask] = 0
    ws = []
    wos = []

    for i in range(193):
        scipy.misc.imsave('static/uploads1/'+str(i) +
                          'wos' + '.jpg', br[:, :, i])

    for o in range(193):
        ws.append(Image.open('static/uploads1/' +
                             str(o)+'ws'+'.jpg').convert('P'))
        wos.append(Image.open('static/uploads1/' +
                              str(o) + 'wos' + '.jpg').convert('P'))

    # ws[0].save('static/uploads1/withskull.gif', save_all=True,  C:\Users\DELL\Desktop\React Work\yfp v3\demoProject\demosite\public\img\back
    save_path = 'C:/Users/DELL/Desktop/React Work/yfp v3/demoProject/demosite/public/img/'+spath+'/'
    if not os.path.exists(save_path):
        os.makedirs(save_path)
    ws[0].save(save_path+'/withskull.gif', save_all=True,
               append_images=ws[1:], optimize=False, duration=60, loop=0)
    wos[0].save(save_path+'/withoutskull.gif', save_all=True,
                append_images=wos[1:], optimize=False, duration=60, loop=0)

    plt.imshow(rawimg[:, :, 80], cmap=plt.get_cmap('gray'))

    # for j in range(193):
    #   os.remove('static/uploads1/'+str(j) + 'wos' + '.jpg')
    #  os.remove('static/uploads1/' + str(j)+'ws'+'.jpg')
    # print("removing files")


def main():
    path = sys.argv[1]
    spath = sys.argv[2]
    print(path)
    print(spath)
    stripping(path, spath)
    print("Working done")


if __name__ == "__main__":
    main()
